# Generated by Django 3.2.10 on 2023-05-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studenDB',
            new_name='studentDB',
        ),
    ]
